#plot of daily HR generated by Smit et al 2016 from Phase II trial
require(tidyverse)
ivm_haz <- read.table("IVM_derivation/ivermectin_hazards.txt", header=TRUE) #Smit Hazard Ratios
colnames(ivm_haz) = c("Day", "IVM_400_1_HS", "IVM_300_3_HS")
ivm_haz <- ivm_haz %>%
  select(-IVM_400_1_HS) %>%
  filter(between(Day, 1, 23))


HR_Smit_plot <- ggplot(ivm_haz, aes(x = Day, y = IVM_300_3_HS))+
  geom_point(size = 2)+
  geom_line(size = 1)+
  theme_bw(base_size = 14)+
  ylab(expression("Hazard ratio of 3×300 "*mu*"g/kg"))+
  geom_hline(yintercept = 1, linetype = "dashed")+
  xlim(0, 25)+
  xlab(expression("Day (" * italic(j) * ")"))

ggsave(HR_Smit_plot, file = "2.ivm-prolonged-distr/plots/sm_fig_4_HR_Smit.pdf")
